#region Local Var
	var uLocal_0 = 0;
	var uLocal_1 = 0;
	int iLocal_2 = 0;
	int iLocal_3 = 0;
	int iLocal_4 = 0;
	int iLocal_5 = 0;
	int iLocal_6 = 0;
	int iLocal_7 = 0;
	int iLocal_8 = 0;
	int iLocal_9 = 0;
	int iLocal_10 = 0;
	int iLocal_11 = 0;
	var uLocal_12 = 0;
	var uLocal_13 = 0;
	float fLocal_14 = 0f;
	var uLocal_15 = 0;
	var uLocal_16 = 0;
	int iLocal_17 = 0;
	int iLocal_18 = 0;
	int iLocal_19 = 0;
#endregion

void __EntryFunction__()
{
	iLocal_2 = 1;
	iLocal_3 = 134;
	iLocal_4 = 134;
	iLocal_5 = 1;
	iLocal_6 = 1;
	iLocal_7 = 1;
	iLocal_8 = 134;
	iLocal_9 = 1;
	iLocal_10 = 12;
	iLocal_11 = 12;
	fLocal_14 = 0.001f;
	iLocal_17 = -1;
	if (PED::REMOVE_SCENARIO_BLOCKING_AREA())
	{
		CAM::DO_SCREEN_FADE_IN(500);
	}
	if (PLAYER::HAS_FORCE_CLEANUP_OCCURRED(3))
	{
		func_5();
	}
	iLocal_19 = unk_0x5DEA4192B46CB99B("instructional_buttons");
	while (!GRAPHICS::HAS_SCALEFORM_MOVIE_LOADED(iLocal_19))
	{
		SYSTEM::WAIT(0);
	}
	while (true)
	{
		GRAPHICS::END_TEXT_COMMAND_SCALEFORM_STRING(iLocal_19, 255, 255, 255, 0, 0);
		func_4();
		func_1(iLocal_18, iLocal_19);
		SYSTEM::WAIT(0);
	}
}

void func_1(int iParam0, int iParam1)
{
	switch (iParam0)
	{
		case 0:
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "CLEAR_ALL");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_CLEAR_SPACE");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(200);
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 191, 1));
			func_2("PRESS A");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(1);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 194, 1));
			func_2("PRESS B");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(2);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 193, 1));
			func_2("PRESS X");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(3);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 192, 1));
			func_2("PRESS Y");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "DRAW_INSTRUCTIONAL_BUTTONS");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_BACKGROUND_COLOUR");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(80);
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			iLocal_18 = -1;
			break;
		
		case 1:
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "CLEAR_ALL");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_CLEAR_SPACE");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(200);
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 187, 1));
			func_2("DOWN");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(1);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 188, 1));
			func_2("UP");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(2);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 190, 1));
			func_2("LEFT");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(3);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 189, 1));
			func_2("RIGHT");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "DRAW_INSTRUCTIONAL_BUTTONS");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_BACKGROUND_COLOUR");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(80);
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			iLocal_18 = -1;
			break;
		
		case 2:
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "CLEAR_ALL");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_CLEAR_SPACE");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(200);
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_DATA_SLOT");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			func_3(MOBILE::GET_MOBILE_PHONE_POSITION(2, 202, 1));
			func_2("BACK");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "DRAW_INSTRUCTIONAL_BUTTONS");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iParam1, "SET_BACKGROUND_COLOUR");
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(0);
			NETWORK::_NETWORK_IS_TEXT_CHAT_ACTIVE(80);
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
			iLocal_18 = -1;
			break;
		
		default:
			break;
	}
}

void func_2(char* sParam0)
{
	MISC::UPDATE_ONSCREEN_KEYBOARD(sParam0);
	GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_FLOAT();
}

void func_3(bool bParam0)
{
	GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_BOOL(bParam0);
}

void func_4()
{
	if (Global_19660 == 0)
	{
		if (((((((((PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 189) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 190)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 188)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 187)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 205)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 206)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 207)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 208)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 201)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 202))
		{
			Global_19660 = 1;
			SYSTEM::SETTIMERA(0);
		}
	}
	else if (SYSTEM::TIMERA() > 50)
	{
		Global_19660 = 0;
	}
	if (Global_19660 == 0)
	{
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 217))
		{
			iLocal_18 = 1;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 189))
		{
			iLocal_18 = 2;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 190))
		{
			iLocal_18 = 2;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 205))
		{
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 206))
		{
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 207))
		{
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 208))
		{
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 188))
		{
			iLocal_18 = 2;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 187))
		{
			iLocal_18 = 2;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 201))
		{
			iLocal_18 = 1;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 202))
		{
			iLocal_18 = 0;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 203))
		{
			iLocal_18 = 1;
		}
		if (PAD::IS_DISABLED_CONTROL_JUST_PRESSED(2, 204))
		{
			iLocal_18 = 1;
		}
	}
}

void func_5()
{
	func_6(0);
	MISC::SET_GAME_PAUSED(false);
	GRAPHICS::SET_SCALEFORM_MOVIE_AS_NO_LONGER_NEEDED(&iLocal_19);
	ENTITY::STOP_ENTITY_ANIM();
}

void func_6(bool bParam0)
{
	if (bParam0)
	{
		func_13();
		if (Global_19681.f_1 == 10 || Global_19681.f_1 == 9)
		{
			unk_0xBE20AB8238688965(&Global_7552, 16);
		}
		Global_19681.f_1 = 1;
		if (func_12(0))
		{
			func_7(0);
		}
	}
	else if (Global_19681.f_1 == 1)
	{
		if (!Global_19681.f_1 == 0)
		{
			Global_19681.f_1 = 3;
		}
	}
}

void func_7(int iParam0)
{
	if (func_11())
	{
		return;
	}
	if (Global_19864)
	{
		if (func_10())
		{
			func_9(1, 1);
		}
		else
		{
			func_9(0, 0);
		}
	}
	if (Global_19681.f_1 == 10 || Global_19681.f_1 == 9)
	{
		unk_0xBE20AB8238688965(&Global_7552, 16);
	}
	if (unk_0x6B12213471F330A3())
	{
		unk_0xBE4122AC23440E7D(0);
	}
	Global_21005 = 5;
	if (iParam0 == 1)
	{
		unk_0xBE20AB8238688965(&Global_7551, 30);
	}
	else
	{
		VEHICLE::IS_VEHICLE_DRIVEABLE(&Global_7551, 30);
	}
	if (!func_8())
	{
		Global_19681.f_1 = 3;
	}
}

int func_8()
{
	if (Global_19681.f_1 == 1 || Global_19681.f_1 == 0)
	{
		return 1;
	}
	return 0;
}

void func_9(bool bParam0, bool bParam1)
{
	if (bParam0)
	{
		if (func_12(0))
		{
			Global_19864 = 1;
			if (bParam1)
			{
				unk_0x1F1B1269BB6217F7(&Global_19618);
			}
			Global_19609 = { Global_19627[Global_19626 /*3*/] };
			AUDIO::SKIP_TO_NEXT_SCRIPTED_CONVERSATION_LINE(Global_19609);
		}
	}
	else if (Global_19864 == 1)
	{
		Global_19864 = 0;
		Global_19609 = { Global_19634[Global_19626 /*3*/] };
		if (bParam1)
		{
			AUDIO::SKIP_TO_NEXT_SCRIPTED_CONVERSATION_LINE(Global_19618);
		}
		else
		{
			AUDIO::SKIP_TO_NEXT_SCRIPTED_CONVERSATION_LINE(Global_19609);
		}
	}
}

bool func_10()
{
	return unk_0xCE990E643CD9D0E5(Global_1689730, 5);
}

bool func_11()
{
	return unk_0xCE990E643CD9D0E5(Global_1689730, 19);
}

int func_12(int iParam0)
{
	if (iParam0 == 1)
	{
		if (Global_19681.f_1 > 3)
		{
			if (unk_0xCE990E643CD9D0E5(Global_7551, 14))
			{
				return 1;
			}
			else
			{
				return 0;
			}
		}
		else
		{
			return 0;
		}
	}
	if (INTERIOR::GET_INTERIOR_AT_COORDS(joaat("cellphone_flashhand")) > 0)
	{
		return 1;
	}
	if (Global_19681.f_1 > 3)
	{
		return 1;
	}
	return 0;
}

void func_13()
{
	if (Global_19681.f_1 == 9 || Global_19681.f_1 == 10)
	{
		Global_21058 = 0;
		Global_21054 = 1;
	}
}

